name: "Setup TFLint"
description: "Install TFLint locally"

runs:
  using: "composite"
  steps:
    - name: Install TFLint
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        sudo mv tflint /usr/local/bin/